# Generated by Django 2.2.6 on 2021-01-15 05:51

import Event.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('wedding', 'Wedding'), ('birthday', 'BirthDay'), ('stage_decoration', 'Stage_Decoration')], default='birthday', max_length=50)),
                ('Max_Guest', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('user_event_request', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Mobile_no', models.IntegerField()),
                ('roll', models.CharField(choices=[('publisher', 'Publisher'), ('enduser', 'EndUser')], default='enduser', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(max_length=255, upload_to=Event.models.image_path)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_photos', to='Event.Event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.UserType'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('indore', 'Indore'), ('ujjain', 'Ujjain'), ('pune', 'Pune'), ('mumbai', 'Mumbai'), ('banglore', 'Banglore'), ('other', 'Other')], default='indore', max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_address', to='Event.Event')),
            ],
        ),
    ]
