# Generated by Django 2.2.6 on 2021-01-04 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_address', to='Event.Event'),
        ),
    ]
