# Generated by Django 2.2.6 on 2021-01-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_auto_20210104_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_event_request',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
